services:
  tts:
    build:
      context: ./services/tts
      dockerfile: Dockerfile
    volumes:
      - data-tts:/home/user/app/data
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  data-tts:
    external: true